fail
Peters-MacBook:flashcards chud$ rake db:seed
attempting to put 'ist' into cards...
rake aborted!
NoMethodError: undefined method `encoding' for nil:NilClass
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/unicode_utils-1.4.0
/lib/unicode_utils/downcase.rb:29:in `downcase'
/Users/chud/flashcards/app/models/card.rb:15:in `texts_are_not_matching'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:192:in `block in simple'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:504:in `block in call'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:504:in `each'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:504:in `call'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.6/l
ib/active_model/validations.rb:399:in `run_validations!'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.6/l
ib/active_model/validations/callbacks.rb:113:in `block in
run_validations!'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:117:in `call'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:505:in `call'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.6/l
ib/active_model/validations/callbacks.rb:113:in `run_validations!'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.6/l
ib/active_model/validations.rb:338:in `valid?'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/validations.rb:58:in `valid?'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/validations.rb:83:in `perform_validations'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/validations.rb:37:in `save'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/attribute_methods/dirty.rb:21:in `save'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/transactions.rb:351:in `block in
with_transaction_returning_status'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/connection_adapters/abstract/database_statements.rb:21
3:in `block in transaction'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/connection_adapters/abstract/transaction.rb:184:in
`within_new_transaction'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/connection_adapters/abstract/database_statements.rb:21
3:in `transaction'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/transactions.rb:220:in `transaction'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/transactions.rb:348:in
`with_transaction_returning_status'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/transactions.rb:286:in `block in save'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/transactions.rb:285:in `save'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/persistence.rb:34:in `create'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/persistence.rb:31:in `block in create'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/persistence.rb:31:in `collect'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/persistence.rb:31:in `create'
/Users/chud/flashcards/db/seeds.rb:84:in `block in <top (required)>'
/Users/chud/flashcards/db/seeds.rb:81:in `each'
/Users/chud/flashcards/db/seeds.rb:81:in `<top (required)>'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/dependencies.rb:268:in `load'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/dependencies.rb:268:in `block in load'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6
/lib/active_support/dependencies.rb:268:in `load'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/
rails/engine.rb:547:in `load_seed'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/chud/flashcards/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/
lib/active_record/railties/databases.rake:183:in `block (2 levels) in
<top (required)>'
/Users/chud/.rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top
(required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)